ci: add GHCR_PAT check

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -11,6 +11,10 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+      - name: Check GHCR_PAT
+        if: ${{ secrets.GHCR_PAT == '' }}
+        run: |
+          echo "GHCR_PAT secret is missing" && exit 1
       - name: Login to GHCR
         uses: docker/login-action@v3
         with:
